spring:
  application:
    name: "homepage"

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: ${USER_ID}
      password: ${USER_PASSWORD}
